# SPDX-License-Identifier: GPL-2.0
#
# Makefile for DisplayLink MA-USB Host driver.
#
# Copyright (c) 2019 - 2020 DisplayLink (UK) Ltd.
#

obj-$(CONFIG_USB_HOST_MAUSB) += mausb_host.o
mausb_host-y := mausb_core.o
mausb_host-y += utils.o
mausb_host-y += ip_link.o
